parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: iariss_jordo
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: fr
    secret: b4d4e038bb1059ed240ecaafa1dbd7ab1
    database_path: null
