thiktak_search:
    resource: "@ThiktakSearchBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_search:
    resource: "@JordoSearchBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_document:
    resource: "@JordoDocumentBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_report:
    resource: "@JordoReportBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_gantt:
    resource: "@JordoGanttBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_print:
    resource: "@JordoPrintBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_notify:
    resource: "@JordoNotifyBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_stats:
    resource: "@JordoStatsBundle/Controller/"
    type:     annotation
    prefix:   /

thiktak_comment:
    resource: "@ThiktakCommentBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_calendar:
    resource: "@JordoCalendarBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_contact:
    resource: "@JordoContactBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_project:
    resource: "@JordoProjectBundle/Controller/"
    type:     annotation
    prefix:   /

thiktak_user:
    resource: "@ThiktakUserBundle/Controller/"
    type:     annotation
    prefix:   /

jordo_member:
    resource: "@JordoUserBundle/Controller/"
    type:     annotation
    prefix:   /

thiktak_core:
    resource: "@ThiktakCoreBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group